
insert into employees (id, name, surname, department) 
values 
(1,'Nina','Lipiński','ProdukcjaA'),
(2,'Mojżesz','Szczerba','ProdukcjaA'),
(3,'Olimpia','Kaniewski','ProdukcjaA'),
(4,'Stanisław','Orłowski','ProdukcjaA'),
(5,'Roger','Grzesiak','ProdukcjaA'),
(6,'Rachela','Szczepanik','ProdukcjaA'),
(7,'Antoni','Zych','ProdukcjaA'),
(8,'Juliusz','Gajda','ProdukcjaA'),
(9,'Eudoksja','Domański','ProdukcjaA'),
(10,'Gwido','Adamiec','ProdukcjaA'),
(11,'Józef','Kuciński','ProdukcjaD'),
(12,'Wilhelm','Leszczyński','ProdukcjaD'),
(13,'Klara','Grześkowiak','ProdukcjaD'),
(14,'Gerazym','Szydłowski','ProdukcjaD'),
(15,'Ada','Wesołowski','ProdukcjaD'),
(16,'Paulina','Rosa','Diagnostyka'),
(17,'Onufry','Włodarczyk','Diagnostyka'),
(18,'Efrem','Lenart','Diagnostyka'),
(19,'Beatrycze','Kowalczyk','Diagnostyka'),
(20,'Damian','Majchrzak','Diagnostyka'),
(21,'Nikola','Chmura','Remonty'),
(22,'Joachim','Cieśla','Remonty'),
(23,'Anastazja','Bujak','Remonty'),
(24,'Łazarz','Kamiński','Remonty'),
(25,'Antoni','Gawlik','Remonty');
